server:
  port: 8888

spring:
  datasource:
    url : jdbc:postgresql://localhost:5432/ecommerce?useSSL=true
    username : postgres
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: update

keycloak:
  auth-server-url: http://localhost:7777/auth
  realm: ecommerce
  resource: ecommerce
  public-client: true
  cors: true