server:
  port: 8888
  servlet:
    context-path: /api

spring:
  flyway:
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost:5432}/${POSTGRES_DB:ecommerce}?useSSL=true
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:123456789}
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        event:
          merge:
            entity_copy_observer: allow
       show-sql: true

  properties:
    hibernate:
      jdbc:
        lob.non_contextual_creation: true
          ddl-auto: update
  application:
    name: Ecommerce-Store
  main:
    allow-bean-definition-overriding: true